class Globalfull {
  String? name;
  String? shortname;
  Globalfull(this.name, this.shortname);
}

List<Globalfull> fullCountriesName = [
  Globalfull("United Arab Emirates", "ae"),
  Globalfull("Argentina", "ar"),
  Globalfull("Austria", "at"),
  Globalfull("Australia", "au"),
  Globalfull("Belgium", "be"),
  Globalfull("Bulgaria", "bg"),
  Globalfull("Brazil", "br"),
  Globalfull("Canada", "ca"),
  Globalfull("Switzerland", "ch"),
  Globalfull("China", "cn"),
  Globalfull("Colombia", "co"),
  Globalfull("Cuba", "cu"),
  Globalfull("The Czech Republic", "cz"),
  Globalfull("Germany", "de"),
  Globalfull("Egypt", "eg"),
  Globalfull("France", "fr"),
  Globalfull("England", "gb"),
  Globalfull("Greece", "gr"),
  Globalfull("Hong Kong", "hk"),
  Globalfull("Hungary", "hu"),
  Globalfull("Indonesia", "id"),
  Globalfull("Ireland", "ie"),
  Globalfull("Israel", "il"),
  Globalfull("India", "in"),
  Globalfull("Italy", "it"),
  Globalfull("Japan", "jp"),
  Globalfull("South Korea", "kr"),
  Globalfull("Lithuania", "lt"),
  Globalfull("Latvia", "lv"),
  Globalfull("Morocco", "ma"),
  Globalfull("Mexico", "mx"),
  Globalfull("Malaysia", "my"),
  Globalfull("Nigeria", "ng"),
  Globalfull("Netherlands", "nl"),
  Globalfull("Norway", "no"),
  Globalfull("New Zealand", "nz"),
  Globalfull("Philippines", "ph"),
  Globalfull("Poland", "pl"),
  Globalfull("Portugal", "pt"),
  Globalfull("Romania", "ro"),
  Globalfull("Serbia", "rs"),
  Globalfull("Russia", "ru"),
  Globalfull("Saudi Arabia", "sa"),
  Globalfull("Sweden", "se"),
  Globalfull("Singapore", "sg"),
  Globalfull("Slovenia", "si"),
  Globalfull("Slovakia", "sk"),
  Globalfull("Thailand", "th"),
  Globalfull("Turkey", "tr"),
  Globalfull("Taiwan", "tw"),
  Globalfull("Ukraine", "ua"),
  Globalfull("United States", "us"),
  Globalfull("Venezuela", "ve"),
  Globalfull("South Africa", "za")
];
